Repository redBorder/cookbook-rb-nmsp, pull requests merged in 2023-10, with the labels that each got.

#5 Modify name of service in consul
  .github/workflows/lint.yml
  Gemfile
  LICENSE
  packaging/rpm/cookbook-rb-nmsp.spec
  resources/attributes/default.rb
  resources/metadata.rb
  resources/providers/config.rb
Labels: size/M, kind/documentation

#6 Development
  resources/attributes/default.rb
  resources/providers/config.rb
Labels: kind/feature, size/S

#7 Adaptations to work on RHEL9
  README.md
  packaging/rpm/cookbook-rb-nmsp.spec
  resources/providers/config.rb
Labels: size/S
